export const JOB_CATEGORIES = [
    { value: "management", label: "مدیریتی" },
    { value: "technical", label: "فنی" },
    { value: "services", label: "خدماتی" },
    { value: "administrative", label: "اداری" },
    { value: "sales", label: "فروش" },
    { value: "support", label: "پشتیبانی" },
    { value: "production", label: "تولیدی" },
    { value: "educational", label: "آموزشی" },
    { value: "health", label: "بهداشتی" },
    { value: "other", label: "سایر" },
];

export const IRAN_PROVINCES = [
    { value: "آذربایجان شرقی", label: "آذربایجان شرقی" },
    { value: "آذربایجان غربی", label: "آذربایجان غربی" },
    { value: "اردبیل", label: "اردبیل" },
    { value: "اصفهان", label: "اصفهان" },
    { value: "البرز", label: "البرز" },
    { value: "ایلام", label: "ایلام" },
    { value: "بوشهر", label: "بوشهر" },
    { value: "تهران", label: "تهران" },
    { value: "چهارمحال و بختیاری", label: "چهارمحال و بختیاری" },
    { value: "خراسان جنوبی", label: "خراسان جنوبی" },
    { value: "خراسان رضوی", label: "خراسان رضوی" },
    { value: "خراسان شمالی", label: "خراسان شمالی" },
    { value: "خوزستان", label: "خوزستان" },
    { value: "زنجان", label: "زنجان" },
    { value: "سمنان", label: "سمنان" },
    { value: "سیستان و بلوچستان", label: "سیستان و بلوچستان" },
    { value: "فارس", label: "فارس" },
    { value: "قزوین", label: "قزوین" },
    { value: "قم", label: "قم" },
    { value: "کردستان", label: "کردستان" },
    { value: "کرمان", label: "کرمان" },
    { value: "کرمانشاه", label: "کرمانشاه" },
    { value: "کهگیلویه و بویراحمد", label: "کهگیلویه و بویراحمد" },
    { value: "گلستان", label: "گلستان" },
    { value: "گیلان", label: "گیلان" },
    { value: "لرستان", label: "لرستان" },
    { value: "مازندران", label: "مازندران" },
    { value: "مرکزی", label: "مرکزی" },
    { value: "هرمزگان", label: "هرمزگان" },
    { value: "همدان", label: "همدان" },
    { value: "یزد", label: "یزد" },
];

